/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;

import javax.swing.JOptionPane;

/**
 *
 * @author Jivan
 */
public class JOptionPaneTut1 extends javax.swing.JFrame
{

    /**
     * Creates new form JOptionPaneTut1
     */
    public JOptionPaneTut1()
    {
        initComponents();
        btnlogin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        btnclick = new javax.swing.JButton();
        btnconfirm = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 204, 255));
        mainPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 255), new java.awt.Color(255, 153, 255), null, null));

        btnclick.setBackground(new java.awt.Color(255, 0, 51));
        btnclick.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnclick.setForeground(new java.awt.Color(255, 255, 51));
        btnclick.setText("CLICK");
        btnclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclick.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnclickActionPerformed(evt);
            }
        });

        btnconfirm.setBackground(new java.awt.Color(255, 0, 51));
        btnconfirm.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(255, 255, 0));
        btnconfirm.setText("CONFIRM");
        btnconfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconfirm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnconfirmActionPerformed(evt);
            }
        });

        btnlogin.setBackground(new java.awt.Color(0, 204, 0));
        btnlogin.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("LOGIN>>");
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnclick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnclick, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnclickActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnclickActionPerformed
    {//GEN-HEADEREND:event_btnclickActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(btnclick, "Button CLicked", "Just Informing", JOptionPane.INFORMATION_MESSAGE);
        
        /*NOTE: -showMessageDialog(ParentComponent, strmessage, titlestring, message_type);
                -showMessageDialog(parentComponent, strmessage);
                -showMessageDialog() is static member function of class JOptionPane.
                -There are different types of messages :-
                   -JOptionPane.PLAIN_MESSAGE
                   -JOptionPane.INFORMATION_MESSAGE
                   -JOptionPane.WARNING_MESSAGE
                   -JOptionPane.ERROR_MESSAGE
                   -JOptionPane.QUESTION_MESSAGE
                   -...etc
        */
    }//GEN-LAST:event_btnclickActionPerformed

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnconfirmActionPerformed
    {//GEN-HEADEREND:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(btnconfirm, "Are You Sure ?", "Just Confirming", JOptionPane.YES_NO_OPTION);
        
        if(JOptionPane.YES_OPTION == res)
        {
            btnlogin.setVisible(true);
        }
        else if(JOptionPane.NO_OPTION == res)
        {
            btnlogin.setVisible(false);
            JOptionPane.showMessageDialog(btnconfirm, "Then get Lost!!");
        }
        
        /*NOTE: -showConfirmDialog(ParentComponent, strmessage, titlestring, option_type);
                -showConfirmDialog(parentComponent, strmessage);
                -showConfirmDialog() is static member function of class JOptionPane.
                -showConfirmDialog() returns an integer which represents user selection. 
                -There are different types of Options :-
                   -JOptionPane.CANCEL_OPTION
                   -JOptionPane.NO_OPTION
                   -JOptionPane.OK_CANCEL_OPTION
                   -JOptionPane.YES_NO_CANCEL_OPTION
                   -JOptionPane.YES_NO_OPTION
                   -JOptionPane.YES_OPTION
                   -JOptionPane.CLOSED_OPTION
                   -...etc
        */
        
    }//GEN-LAST:event_btnconfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JOptionPaneTut1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JOptionPaneTut1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JOptionPaneTut1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JOptionPaneTut1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JOptionPaneTut1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclick;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btnlogin;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
