/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Jivan
 */
public class LoginFrame1 extends javax.swing.JFrame
{

    JLabel lblusername, lblpassword;
    JTextField txtusername;
    JPasswordField txtpasswordField;
    JButton btnlogin;
    
    public LoginFrame1()
    {
        initComponents();
        //adding Components on Label Manually
        initialize();
        //adding image to lbllogin
        CommonFunctions.addLabelBackground(lbllogin, "D:\\A_REGAL_CLASSES\\JAVA_CLASS\\NetBeansProjects\\MyFirstProject\\src\\main\\java\\Mypackage\\Images\\loginbox2.png");
    }
    
    private void initialize()
    {
        Font f = new Font("verdena", Font.BOLD, 18);
        Font f1 = new Font("verdena", Font.BOLD, 12);
        //adding Labels
        lblusername = new JLabel("USERNAME ::");
        lblusername.setBounds(20,60,140,30);
        lblusername.setFont(f);
        lblusername.setForeground(Color.white);
        lbllogin.add(lblusername);
        
        lblpassword = new JLabel("PASSWORD ::");
        lblpassword.setBounds(20,120,140,30);
        lblpassword.setFont(f);
        lblpassword.setForeground(Color.white);
        lbllogin.add(lblpassword);
        
        //adding TextFields
        txtusername = new JTextField();
        txtusername.setBounds(150,60,200,30);
        txtusername.setFont(f1);
        txtusername.requestFocus();
        lbllogin.add(txtusername);
     
        txtpasswordField = new JPasswordField();
        txtpasswordField.setBounds(150,120,200,30);
        txtpasswordField.setFont(f1);
        txtpasswordField.setEchoChar('*');
        lbllogin.add(txtpasswordField);
        
        //adding Button 
        btnlogin = new JButton("LOGIN");
        btnlogin.setBounds(105,200,140,40);
        btnlogin.setFont(f);
        btnlogin.setBackground(Color.red);
        btnlogin.setForeground(Color.white);
        btnlogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lbllogin.add(btnlogin);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbllogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        lbllogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 102), new java.awt.Color(102, 0, 102)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbllogin, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbllogin, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LoginFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbllogin;
    // End of variables declaration//GEN-END:variables
}
