/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;

/**
 *
 * @author Jivan
 */
public class MenuBar extends javax.swing.JFrame
{

    /**
     * Creates new form MenuBar
     */
    public MenuBar()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        myMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newProjectMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        importProjectSubMenu = new javax.swing.JMenu();
        eclipseSubMenu = new javax.swing.JMenu();
        project1MenuItem = new javax.swing.JMenuItem();
        project2MenuItem = new javax.swing.JMenuItem();
        project3MenuItem = new javax.swing.JMenuItem();
        zipMenuItem = new javax.swing.JMenuItem();
        closeMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        layoutSubMenu = new javax.swing.JMenu();
        absoluteMenuItem = new javax.swing.JMenuItem();
        freeMenuItem = new javax.swing.JMenuItem();
        showMenuItem = new javax.swing.JMenuItem();
        deleteSubMenu = new javax.swing.JMenu();
        deleteFileMenuItem = new javax.swing.JMenuItem();
        deleteProjectMenuItem = new javax.swing.JMenuItem();
        historyMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        toolMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU_BAR");

        mainPanel.setBackground(new java.awt.Color(255, 204, 204));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        mainPanel.setToolTipText("");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        myMenuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        fileMenu.setText("File");

        newProjectMenuItem.setText("New Project");
        fileMenu.add(newProjectMenuItem);

        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        importProjectSubMenu.setText("Import Project");

        eclipseSubMenu.setText("Eclipse");

        project1MenuItem.setText("Project1");
        eclipseSubMenu.add(project1MenuItem);

        project2MenuItem.setText("Project2");
        eclipseSubMenu.add(project2MenuItem);

        project3MenuItem.setText("Project3");
        eclipseSubMenu.add(project3MenuItem);

        importProjectSubMenu.add(eclipseSubMenu);

        zipMenuItem.setText("From Zip");
        importProjectSubMenu.add(zipMenuItem);

        fileMenu.add(importProjectSubMenu);

        closeMenuItem.setText("Close");
        fileMenu.add(closeMenuItem);

        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        myMenuBar.add(fileMenu);

        editMenu.setText("Edit");

        layoutSubMenu.setText("Layout");

        absoluteMenuItem.setText("Absolute");
        layoutSubMenu.add(absoluteMenuItem);

        freeMenuItem.setText("Free");
        layoutSubMenu.add(freeMenuItem);

        editMenu.add(layoutSubMenu);

        showMenuItem.setText("Show");
        editMenu.add(showMenuItem);

        deleteSubMenu.setText("Delete");

        deleteFileMenuItem.setText("delete file");
        deleteSubMenu.add(deleteFileMenuItem);

        deleteProjectMenuItem.setText("delete project");
        deleteSubMenu.add(deleteProjectMenuItem);

        editMenu.add(deleteSubMenu);

        historyMenuItem.setText("History");
        editMenu.add(historyMenuItem);

        myMenuBar.add(editMenu);

        viewMenu.setText("View");
        myMenuBar.add(viewMenu);

        toolMenu.setBorder(null);
        toolMenu.setText("Tools");
        myMenuBar.add(toolMenu);

        setJMenuBar(myMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MenuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem absoluteMenuItem;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JMenuItem deleteFileMenuItem;
    private javax.swing.JMenuItem deleteProjectMenuItem;
    private javax.swing.JMenu deleteSubMenu;
    private javax.swing.JMenu eclipseSubMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem freeMenuItem;
    private javax.swing.JMenuItem historyMenuItem;
    private javax.swing.JMenu importProjectSubMenu;
    private javax.swing.JMenu layoutSubMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar myMenuBar;
    private javax.swing.JMenuItem newProjectMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem project1MenuItem;
    private javax.swing.JMenuItem project2MenuItem;
    private javax.swing.JMenuItem project3MenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem showMenuItem;
    private javax.swing.JMenu toolMenu;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem zipMenuItem;
    // End of variables declaration//GEN-END:variables
}
