/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;

import javax.swing.JOptionPane;

/**
 *
 * @author Jivan
 */
public class TabbedPaneCalculator extends javax.swing.JFrame
{

    /**
     * Creates new form TabbedPaneCalculator
     */
    public TabbedPaneCalculator()
    {
        initComponents();
        CommonFunctions.addLabelBackground(lblplusIcon, "D:\\A_REGAL_CLASSES\\JAVA_CLASS\\NetBeansProjects\\MyFirstProject\\src\\main\\java\\Mypackage\\Images\\red_plus_icon.png");
        CommonFunctions.addLabelBackground(lblminusIcon, "D:\\A_REGAL_CLASSES\\JAVA_CLASS\\NetBeansProjects\\MyFirstProject\\src\\main\\java\\Mypackage\\Images\\red_minus_icon.png");
        CommonFunctions.addLabelBackground(lblmulIcon, "D:\\A_REGAL_CLASSES\\JAVA_CLASS\\NetBeansProjects\\MyFirstProject\\src\\main\\java\\Mypackage\\Images\\red_mul_icon.png");
        CommonFunctions.addLabelBackground(lbldivIcon, "D:\\A_REGAL_CLASSES\\JAVA_CLASS\\NetBeansProjects\\MyFirstProject\\src\\main\\java\\Mypackage\\Images\\red_div_icon.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        calculatorTabbedPane = new javax.swing.JTabbedPane();
        addPanel = new javax.swing.JPanel();
        txtnum1 = new javax.swing.JTextField();
        txtnum2 = new javax.swing.JTextField();
        lblnum1 = new javax.swing.JLabel();
        lblnum2 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        lblans = new javax.swing.JLabel();
        lblplusIcon = new javax.swing.JLabel();
        subPanel = new javax.swing.JPanel();
        txtsubnum1 = new javax.swing.JTextField();
        txtsubnum2 = new javax.swing.JTextField();
        btnsub = new javax.swing.JButton();
        lblsubnum = new javax.swing.JLabel();
        lblsubnum2 = new javax.swing.JLabel();
        lblans2 = new javax.swing.JLabel();
        lblminusIcon = new javax.swing.JLabel();
        mulPanel = new javax.swing.JPanel();
        txtmulnum1 = new javax.swing.JTextField();
        txtmulnum2 = new javax.swing.JTextField();
        lblmulnum1 = new javax.swing.JLabel();
        lblmulnum2 = new javax.swing.JLabel();
        btnmul = new javax.swing.JButton();
        lblans3 = new javax.swing.JLabel();
        lblmulIcon = new javax.swing.JLabel();
        divPanel = new javax.swing.JPanel();
        txtdivnum1 = new javax.swing.JTextField();
        txtdivnum2 = new javax.swing.JTextField();
        lbldivnum1 = new javax.swing.JLabel();
        lbldivnum2 = new javax.swing.JLabel();
        btndiv = new javax.swing.JButton();
        lblans4 = new javax.swing.JLabel();
        lbldivIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");

        mainPanel.setBackground(new java.awt.Color(255, 204, 204));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));

        calculatorTabbedPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        calculatorTabbedPane.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        addPanel.setBackground(new java.awt.Color(204, 255, 255));

        txtnum1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnum1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtnum1KeyTyped(evt);
            }
        });

        txtnum2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnum2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtnum2KeyTyped(evt);
            }
        });

        lblnum1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblnum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnum1.setText("NUMBER-1");
        lblnum1.setToolTipText("");

        lblnum2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblnum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnum2.setText("NUMBER-2");
        lblnum2.setToolTipText("");

        btnadd.setBackground(new java.awt.Color(255, 0, 51));
        btnadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 0));
        btnadd.setText("ADD");
        btnadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnaddActionPerformed(evt);
            }
        });

        lblans.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblans.setText("ANSWER HERE");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(lblplusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(lblnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(txtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(txtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblplusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblans, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        calculatorTabbedPane.addTab("ADDITION", addPanel);

        subPanel.setBackground(new java.awt.Color(255, 204, 255));

        txtsubnum1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsubnum1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtsubnum1KeyTyped(evt);
            }
        });

        txtsubnum2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsubnum2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtsubnum2KeyTyped(evt);
            }
        });

        btnsub.setBackground(new java.awt.Color(255, 0, 51));
        btnsub.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnsub.setForeground(new java.awt.Color(255, 255, 0));
        btnsub.setText("SUB");
        btnsub.setBorder(null);
        btnsub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsub.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsubActionPerformed(evt);
            }
        });

        lblsubnum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblsubnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsubnum.setText("NUMBER-2");

        lblsubnum2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblsubnum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsubnum2.setText("NUMBER-1");

        lblans2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblans2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblans2.setText("ANSWER HERE");

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE))
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblans2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(subPanelLayout.createSequentialGroup()
                                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsubnum1)
                                    .addComponent(lblsubnum2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblsubnum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsubnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblminusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsubnum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsubnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblans2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblminusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        calculatorTabbedPane.addTab("SUBSTRACTION", subPanel);

        mulPanel.setBackground(new java.awt.Color(255, 255, 204));

        txtmulnum1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmulnum1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtmulnum1KeyTyped(evt);
            }
        });

        txtmulnum2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmulnum2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtmulnum2KeyTyped(evt);
            }
        });

        lblmulnum1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblmulnum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmulnum1.setText("NUMBER-1");

        lblmulnum2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblmulnum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmulnum2.setText("NUMBER-2");

        btnmul.setBackground(new java.awt.Color(255, 0, 51));
        btnmul.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnmul.setForeground(new java.awt.Color(255, 255, 51));
        btnmul.setText("MUL");
        btnmul.setBorder(null);
        btnmul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmul.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnmulActionPerformed(evt);
            }
        });

        lblans3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblans3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblans3.setText("ANSWER HERE");

        javax.swing.GroupLayout mulPanelLayout = new javax.swing.GroupLayout(mulPanel);
        mulPanel.setLayout(mulPanelLayout);
        mulPanelLayout.setHorizontalGroup(
            mulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mulPanelLayout.createSequentialGroup()
                .addGroup(mulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mulPanelLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mulPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(mulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblans3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mulPanelLayout.createSequentialGroup()
                                .addGroup(mulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblmulnum1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(txtmulnum1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addGroup(mulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmulnum2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(lblmulnum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmulIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mulPanelLayout.setVerticalGroup(
            mulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mulPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(mulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmulnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmulnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmulnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmulnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblans3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mulPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblmulIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        calculatorTabbedPane.addTab("MULTIPLICATION", mulPanel);

        divPanel.setBackground(new java.awt.Color(204, 255, 204));

        txtdivnum1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdivnum1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtdivnum1KeyTyped(evt);
            }
        });

        txtdivnum2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdivnum2.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtdivnum2KeyTyped(evt);
            }
        });

        lbldivnum1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbldivnum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldivnum1.setText("NUMBER-1");

        lbldivnum2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbldivnum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldivnum2.setText("NUMBER-2");

        btndiv.setBackground(new java.awt.Color(255, 0, 0));
        btndiv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btndiv.setForeground(new java.awt.Color(255, 255, 51));
        btndiv.setText("DIV");
        btndiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndiv.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btndivActionPerformed(evt);
            }
        });

        lblans4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblans4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblans4.setText("ANSWER HERE");

        javax.swing.GroupLayout divPanelLayout = new javax.swing.GroupLayout(divPanel);
        divPanel.setLayout(divPanelLayout);
        divPanelLayout.setHorizontalGroup(
            divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divPanelLayout.createSequentialGroup()
                .addGroup(divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(divPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE))
                    .addGroup(divPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblans4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(divPanelLayout.createSequentialGroup()
                                .addGroup(divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbldivnum1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(txtdivnum1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdivnum2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(lbldivnum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldivIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        divPanelLayout.setVerticalGroup(
            divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldivnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldivnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(divPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdivnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdivnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblans4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbldivIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        calculatorTabbedPane.addTab("DIVISION", divPanel);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(calculatorTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(calculatorTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnum2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtnum2KeyTyped
    {//GEN-HEADEREND:event_txtnum2KeyTyped
        // TODO add your handling code here:
        CommonFunctions.numericValidation(evt);
    }//GEN-LAST:event_txtnum2KeyTyped

    private void txtnum1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtnum1KeyTyped
    {//GEN-HEADEREND:event_txtnum1KeyTyped
        // TODO add your handling code here:
        CommonFunctions.numericValidation(evt);
    }//GEN-LAST:event_txtnum1KeyTyped

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnaddActionPerformed
    {//GEN-HEADEREND:event_btnaddActionPerformed
        // TODO add your handling code here:
        String str1, str2;
        str1 = txtnum1.getText();
        str2 = txtnum2.getText();
        try
        {
            double x = Double.parseDouble(str1);
            double y = Double.parseDouble(str2);
            double ans = x + y;
            Double ansRoundOff = Math.round(ans*100.0)/100.0;      //To Round off ans upto 2 digits after decimal
            lblans.setText("ADDITION = " + ansRoundOff);
        }
        catch(NumberFormatException ne)
        {
            txtnum1.setText("");
            txtnum2.setText("");
            lblans.setText("ANSWER HERE");
            JOptionPane.showMessageDialog(btnadd, "Invalid Data", "ErrorMessage", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtsubnum1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtsubnum1KeyTyped
    {//GEN-HEADEREND:event_txtsubnum1KeyTyped
        // TODO add your handling code here:
        CommonFunctions.numericValidation(evt);
    }//GEN-LAST:event_txtsubnum1KeyTyped

    private void txtsubnum2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtsubnum2KeyTyped
    {//GEN-HEADEREND:event_txtsubnum2KeyTyped
        // TODO add your handling code here:
        CommonFunctions.numericValidation(evt);
    }//GEN-LAST:event_txtsubnum2KeyTyped

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsubActionPerformed
    {//GEN-HEADEREND:event_btnsubActionPerformed
        // TODO add your handling code here:
        String str1, str2;
        str1 = txtsubnum1.getText();
        str2 = txtsubnum2.getText();
        try
        {
            double x = Double.parseDouble(str1);
            double y = Double.parseDouble(str2);
            double ans = x - y;
            Double ansRoundOff = Math.round(ans*100.0)/100.0;      //To Round off ans upto 2 digits after decimal
            lblans2.setText("SUBSTRACTION = " + ansRoundOff);
        }
        catch(NumberFormatException ne)
        {
            txtsubnum1.setText("");
            txtsubnum2.setText("");
            lblans2.setText("ANSWER HERE");
            JOptionPane.showMessageDialog(btnsub, "Invalid Data", "ErrorMessage", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsubActionPerformed

    private void txtmulnum1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtmulnum1KeyTyped
    {//GEN-HEADEREND:event_txtmulnum1KeyTyped
        // TODO add your handling code here:
        CommonFunctions.numericValidation(evt);
    }//GEN-LAST:event_txtmulnum1KeyTyped

    private void txtmulnum2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtmulnum2KeyTyped
    {//GEN-HEADEREND:event_txtmulnum2KeyTyped
        // TODO add your handling code here:
        CommonFunctions.numericValidation(evt);
    }//GEN-LAST:event_txtmulnum2KeyTyped

    private void btnmulActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnmulActionPerformed
    {//GEN-HEADEREND:event_btnmulActionPerformed
        // TODO add your handling code here:
        String str1, str2;
        str1 = txtmulnum1.getText();
        str2 = txtmulnum2.getText();
        try
        {
            double x = Double.parseDouble(str1);
            double y = Double.parseDouble(str2);
            double ans = x * y;
            Double ansRoundOff = Math.round(ans*100.0)/100.0;      //To Round off ans upto 2 digits after decimal
            lblans3.setText("MULTIPLICATION = " + ansRoundOff);
        }
        catch(NumberFormatException ne)
        {
            txtmulnum1.setText("");
            txtmulnum2.setText("");
            lblans3.setText("ANSWER HERE");
            JOptionPane.showMessageDialog(btnmul, "Invalid Data", "ErrorMessage", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnmulActionPerformed

    private void txtdivnum1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtdivnum1KeyTyped
    {//GEN-HEADEREND:event_txtdivnum1KeyTyped
        // TODO add your handling code here:
        CommonFunctions.numericValidation(evt);
    }//GEN-LAST:event_txtdivnum1KeyTyped

    private void txtdivnum2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtdivnum2KeyTyped
    {//GEN-HEADEREND:event_txtdivnum2KeyTyped
        // TODO add your handling code here:
        CommonFunctions.numericValidation(evt);
    }//GEN-LAST:event_txtdivnum2KeyTyped

    private void btndivActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btndivActionPerformed
    {//GEN-HEADEREND:event_btndivActionPerformed
        // TODO add your handling code here:
        String str1, str2;
        str1 = txtdivnum1.getText();
        str2 = txtdivnum2.getText();
        try
        {
            double x = Double.parseDouble(str1);
            double y = Double.parseDouble(str2);
            double ans = x / y;
            if(y != 0.0)                //i.e. if denominator is not zero
            {
                Double ansRoundOff = Math.round(ans*100.0)/100.0;      //To Round off ans upto 2 digits after decimal
                lblans4.setText("DIVISION = " + ansRoundOff);
            }
            else
                lblans4.setText("DIVISION = " + ans);
        }
        catch(NumberFormatException ne)
        {
            txtdivnum1.setText("");
            txtdivnum2.setText("");
            lblans4.setText("ANSWER HERE");
            JOptionPane.showMessageDialog(btndiv, "Invalid Data", "ErrorMessage", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btndivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TabbedPaneCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TabbedPaneCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TabbedPaneCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TabbedPaneCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TabbedPaneCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnmul;
    private javax.swing.JButton btnsub;
    private javax.swing.JTabbedPane calculatorTabbedPane;
    private javax.swing.JPanel divPanel;
    private javax.swing.JLabel lblans;
    private javax.swing.JLabel lblans2;
    private javax.swing.JLabel lblans3;
    private javax.swing.JLabel lblans4;
    private javax.swing.JLabel lbldivIcon;
    private javax.swing.JLabel lbldivnum1;
    private javax.swing.JLabel lbldivnum2;
    private javax.swing.JLabel lblminusIcon;
    private javax.swing.JLabel lblmulIcon;
    private javax.swing.JLabel lblmulnum1;
    private javax.swing.JLabel lblmulnum2;
    private javax.swing.JLabel lblnum1;
    private javax.swing.JLabel lblnum2;
    private javax.swing.JLabel lblplusIcon;
    private javax.swing.JLabel lblsubnum;
    private javax.swing.JLabel lblsubnum2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mulPanel;
    private javax.swing.JPanel subPanel;
    private javax.swing.JTextField txtdivnum1;
    private javax.swing.JTextField txtdivnum2;
    private javax.swing.JTextField txtmulnum1;
    private javax.swing.JTextField txtmulnum2;
    private javax.swing.JTextField txtnum1;
    private javax.swing.JTextField txtnum2;
    private javax.swing.JTextField txtsubnum1;
    private javax.swing.JTextField txtsubnum2;
    // End of variables declaration//GEN-END:variables
}
